MODEL:
    NUM_CLASSES: 11
    BACKBONE:
        NAME: 'mynet'
        PRETRAINED: False
        OUT_CHANNELS: [256, 256, 256, 512, 512, 1024]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("mnist_detection_train", "mnist_detection_val")
    TEST: ("mnist_detection_val", )
SOLVER:
    MAX_ITER: 10000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 2e-3
OUTPUT_DIR: 'outputs/mynet'
DATASET_DIR: "datasets"