MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext'
        PRETRAINED: True
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [512, 1024, 2048]
    PRIORS:
        #FEATURE_MAPS: [[38, 38], [19, 19], [10, 10], ]
        FEATURE_MAPS: [[63, 63], [32, 32], [16, 16], ]
INPUT:
    #IMAGE_SIZE: [300, 300]
    IMAGE_SIZE: [300, 300]
    PIXEL_STD: [0.229, 0.224, 0.225] 
    PIXEL_MEAN: [0.485, 0.456, 0.406]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 25000
    GAMMA: 0.1
    BATCH_SIZE: 10
    LR: 1e-4
  
OUTPUT_DIR: 'outputs/rdd2020_resnext50_bigger_aug_loss'
EVAL_STEP: 2500
MODEL_SAVE_STEP: 2500
DATASET_DIR: "/work/datasets/"