MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'inception'
        PRETRAINED: True
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [288, 768, 1280, 2048, 2048]
    PRIORS:        
        FEATURE_MAPS: [[35, 35], [17, 17], [8, 8], [8, 8], [8, 8],] #300x300
INPUT:
    IMAGE_SIZE: [300, 300]
    #IMAGE_SIZE: [640, 480]
    PIXEL_STD: [0.229, 0.224, 0.225] 
    PIXEL_MEAN: [0.485, 0.456, 0.406]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 50000
    GAMMA: 0.1
    BATCH_SIZE: 10
    LR: 1e-4
  
OUTPUT_DIR: 'outputs/rdd2020_inception_v3'
EVAL_STEP: 500
MODEL_SAVE_STEP: 500
DATASET_DIR: "datasets/"