MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext'
        PRETRAINED: True
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [512, 1024, 2048]
    PRIORS:
        FEATURE_MAPS: [[80, 45], [40, 23], [20, 12], ] #640x360
        MIN_SIZES: [[10, 10], [60, 60], [120, 120]]
        MAX_SIZES: [[60, 60], [120, 120], [220, 220]]
        ASPECT_RATIOS: [[2,3], [2,3], [2,3,4]]
        BOXES_PER_LOCATION: [6, 6, 8]  # number of boxes per feature map location
INPUT:
    #IMAGE_SIZE: [300, 300]
    IMAGE_SIZE: [640, 360]
    #IMAGE_SIZE: [640, 360]
    PIXEL_STD: [0.229, 0.224, 0.225] 
    PIXEL_MEAN: [0.485, 0.456, 0.406]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 30000
    GAMMA: 0.1
    BATCH_SIZE: 10
    LR: 1e-4
  
OUTPUT_DIR: 'outputs/tdt4265_resnext50_prioris_transfer_learn'
EVAL_STEP: 1000
MODEL_SAVE_STEP: 1000